const $=id=>document.getElementById(id), els={contract:$('contract'),road:$('road'),service:$('service'),period:$('period'),sort:$('sort'),search:$('search')};
const DEFAULT_CONTRACT=MALHA.some(x=>x.contrato==='2476')?'2476':MALHA[0]?.contrato||'Todos';
const PAGE_SIZE=8;let page=1,updating=false;
const uniq=a=>[...new Set(a)];
const fmt=n=>Number(n||0).toLocaleString('pt-BR',{minimumFractionDigits:0,maximumFractionDigits:2});
const kmFmt=n=>fmt(n)+' km';
const short=n=>{n=Number(n||0);return Math.abs(n)>=1e6?fmt(n/1e6)+' mi':Math.abs(n)>=1e3?fmt(n/1e3)+' mil':fmt(n)};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const periodLabel=p=>p==='Todos'?'Todos os períodos':(/^\d{4}-\d{2}$/.test(p)?new Date(p+'-01T12:00:00').toLocaleDateString('pt-BR',{month:'short',year:'numeric'}):p);
const merge=ints=>{const a=ints.map(x=>[Math.min(x[0],x[1]),Math.max(x[0],x[1])]).sort((x,y)=>x[0]-y[0]),o=[];for(const x of a){if(!o.length||x[0]>o[o.length-1][1]+.001)o.push([...x]);else o[o.length-1][1]=Math.max(o[o.length-1][1],x[1])}return o};
const unionLen=ints=>merge(ints).reduce((t,x)=>t+x[1]-x[0],0);
function groupMalha(rows){const mp=new Map();for(const r of rows){const k=r.contrato+'|'+r.rodovia;if(!mp.has(k))mp.set(k,{contrato:r.contrato,rodovia:r.rodovia,intervals:[]});mp.get(k).intervals.push([r.kmi,r.kmf])}return [...mp.values()].map(g=>{g.intervals=merge(g.intervals);g.start=Math.min(...g.intervals.map(x=>x[0]));g.end=Math.max(...g.intervals.map(x=>x[1]));g.ext=unionLen(g.intervals);return g})}
function qtyMatches(q,sel,ignore=''){if(ignore!=='contract'&&sel.contract!=='Todos'&&q.contrato!==sel.contract)return false;if(ignore!=='period'&&sel.period!=='Todos'&&q.periodo!==sel.period)return false;if(ignore!=='service'&&sel.service!=='Todos'&&q.servico!==sel.service)return false;if(ignore!=='road'&&sel.road!=='Todas'&&!(q.rodovias||[]).includes(sel.road))return false;return true}
function detailMatches(d,sel){return (sel.contract==='Todos'||d.contrato===sel.contract)&&(sel.road==='Todas'||d.rodovia===sel.road)&&(sel.service==='Todos'||d.servico===sel.service)&&(sel.period==='Todos'||d.periodo===sel.period)}
function malhaMatches(m,sel){return (sel.contract==='Todos'||m.contrato===sel.contract)&&(sel.road==='Todas'||m.rodovia===sel.road)}
function selections(){return{contract:els.contract.value||'Todos',road:els.road.value||'Todas',service:els.service.value||'Todos',period:els.period.value||'Todos'}}
function setOptions(el,values,allValue,allLabel,current){const opts=[[allValue,allLabel],...values.map(v=>[v,v])];el.innerHTML=opts.map(([v,l])=>`<option value="${esc(v)}">${esc(el===els.period?periodLabel(l):l)}</option>`).join('');el.value=opts.some(x=>x[0]===current)?current:allValue}
function refreshFacets(trigger){if(updating)return;updating=true;const s=selections();
 const contracts=uniq(MALHA.filter(m=>(s.road==='Todas'||m.rodovia===s.road)).map(m=>m.contrato)).sort();
 const oldC=els.contract.value;setOptions(els.contract,contracts,'Todos','Todos os contratos',oldC);
 const s1=selections();const roads=uniq(MALHA.filter(m=>(s1.contract==='Todos'||m.contrato===s1.contract)).map(m=>m.rodovia)).sort((a,b)=>a.localeCompare(b,'pt-BR',{numeric:true}));const oldR=els.road.value;setOptions(els.road,roads,'Todas','Todas as rodovias',oldR);
 const s2=selections();const services=uniq(QTY.filter(q=>(s2.contract==='Todos'||q.contrato===s2.contract)&&(s2.road==='Todas'||(q.rodovias||[]).includes(s2.road))&&(s2.period==='Todos'||q.periodo===s2.period)).map(q=>q.servico)).sort((a,b)=>a.localeCompare(b,'pt-BR'));const oldS=els.service.value;setOptions(els.service,services,'Todos','Todas as famílias',oldS);
 const s3=selections();const periods=uniq(QTY.filter(q=>(s3.contract==='Todos'||q.contrato===s3.contract)&&(s3.road==='Todas'||(q.rodovias||[]).includes(s3.road))&&(s3.service==='Todos'||q.servico===s3.service)).map(q=>q.periodo).filter(Boolean)).sort().reverse();const oldP=els.period.value;setOptions(els.period,periods,'Todos','Todos os períodos',oldP);
 updating=false}
function filteredMalha(){const s=selections(),q=els.search.value.trim().toLowerCase();return MALHA.filter(m=>malhaMatches(m,s)&&(!q||m.rodovia.toLowerCase().includes(q)||m.contrato.includes(q)))}
function filteredQty(){const s=selections();return QTY.filter(q=>qtyMatches(q,s))}
function filteredDetail(){const s=selections();return DETAIL.filter(d=>detailMatches(d,s))}
function serviceTotal(rows,service){return rows.filter(r=>r.servico===service).reduce((t,r)=>t+Number(r.quantidade||0),0)}
function topServices(rows,limit=3){const mp=new Map();for(const r of rows)mp.set(r.servico,(mp.get(r.servico)||0)+Number(r.quantidade||0));return [...mp.entries()].sort((a,b)=>b[1]-a[1]).slice(0,limit)}
function iconSvg(type){const icons={route:'<svg viewBox="0 0 24 24"><path d="M4 20 9 4h6l5 16M8 12h8"/></svg>',task:'<svg viewBox="0 0 24 24"><path d="M9 11l2 2 4-4"/><path d="M5 4h14v16H5z"/><path d="M9 4V2h6v2"/></svg>',chart:'<svg viewBox="0 0 24 24"><path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/></svg>'};return icons[type]||icons.chart}
function updateTopKpis(rows){const top=topServices(rows,3);for(let i=0;i<3;i++){const el=$('topKpi'+(i+1)),item=top[i];if(!item){el.innerHTML=`<div class="icon yellow">${iconSvg('task')}</div><div class="kpi-copy"><div class="kpi-label">Sem item executado</div><div class="kpi-value">-</div><div class="kpi-note">para o filtro atual</div></div>`;continue}el.title=item[0];el.innerHTML=`<div class="icon green">${iconSvg(i===0?'chart':'task')}</div><div class="kpi-copy"><div class="kpi-label">${esc(item[0])}</div><div class="kpi-value">${short(item[1])}</div><div class="kpi-note">quantidade executada</div></div>`}}
function relevantLanes(g,details,qtyRows){const s=selections();if(s.service!=='Todos')return[s.service];const services=uniq(details.filter(d=>d.contrato===g.contrato&&d.rodovia===g.rodovia).map(d=>d.servico));return services.sort((a,b)=>serviceTotal(qtyRows,b)-serviceTotal(qtyRows,a)).slice(0,4)}
function contractSegments(g,range){return g.intervals.map(([a,b])=>`<i class="contract-seg" style="left:${(a-g.start)/range*100}%;width:${Math.max((b-a)/range*100,.25)}%"></i>`).join('')}
function executionSegments(g,service,details,range){const ds=details.filter(d=>d.contrato===g.contrato&&d.rodovia===g.rodovia&&(service==='__ALL__'||d.servico===service));const intervals=merge(ds.filter(d=>d.kmf>d.kmi).map(d=>[d.kmi,d.kmf]));const points=ds.filter(d=>d.kmf===d.kmi).map(d=>d.kmi);let h=intervals.map(([a,b])=>{const matches=ds.filter(d=>d.kmi<=b&&d.kmf>=a);const obs=uniq(matches.map(d=>d.observacao)).slice(0,2).join(' | ');return `<i class="done-seg" title="${esc(service)} | Km ${fmt(a)} ao Km ${fmt(b)}${obs?' | '+obs:''}" style="left:${(a-g.start)/range*100}%;width:${Math.max((b-a)/range*100,.45)}%"></i>`}).join('');h+=points.map(p=>`<i class="done-seg" title="${esc(service)} | ponto no Km ${fmt(p)}" style="left:${(p-g.start)/range*100}%;width:.6%"></i>`).join('');return h}
function serviceLocationText(g,service,details){const ds=details.filter(d=>d.contrato===g.contrato&&d.rodovia===g.rodovia&&d.servico===service);const intervals=merge(ds.filter(d=>d.kmf>d.kmi).map(d=>[d.kmi,d.kmf]));const points=uniq(ds.filter(d=>d.kmf===d.kmi).map(d=>d.kmi)).sort((a,b)=>a-b);const parts=intervals.map(([a,b])=>`Km ${fmt(a)}–${fmt(b)}`);points.forEach(p=>parts.push(`Km ${fmt(p)}`));return parts.join(' • ')}
function renderRoad(g,details,qtyRows){const range=Math.max(g.end-g.start,.0001),base=contractSegments(g,range),lanes=relevantLanes(g,details,qtyRows);let laneHtml='';if(!lanes.length){laneHtml=`<div class="no-exec">Sem família/serviço com execução localizada nesta rodovia para os filtros selecionados.</div>`}else{laneHtml=lanes.map(s=>{const total=serviceTotal(qtyRows.filter(q=>q.contrato===g.contrato&&(q.rodovias||[]).includes(g.rodovia)),s),where=serviceLocationText(g,s,details);return `<div class="lane"><div class="lane-name" title="${esc(s)}">${esc(s)}</div><div class="lane-track">${base}${executionSegments(g,s,details,range)}</div><div class="lane-total"><strong>Qtd. ${short(total)}</strong><span title="${esc(where)}">${esc(where||'Sem KM localizado')}</span></div></div>`}).join('')}
 const more=selections().service==='Todos'?uniq(details.filter(d=>d.contrato===g.contrato&&d.rodovia===g.rodovia).map(d=>d.servico)).length-lanes.length:0;
 const code=g.rodovia.replace('-','<br>');return `<article class="road"><div class="road-top"><div class="road-id"><div class="shield">${code}</div><div><div class="road-name">${g.rodovia}</div><span class="chip">Contrato ${g.contrato}</span></div></div><div class="ext">${kmFmt(g.ext)}<span>de extensão</span></div></div><div class="road-scale"><span class="km">Km ${fmt(g.start)}</span><div class="scale-track">${base}${executionSegments(g,selections().service==='Todos'?'__ALL__':selections().service,details,range)}</div><span class="km end">Km ${fmt(g.end)}</span></div><div class="lane-wrap">${laneHtml}${more>0?`<div class="more-lanes">+ ${more} família(s) com execução; selecione no filtro para detalhar.</div>`:''}</div></article>`}
function coverageFor(g,details){const s=selections();const ds=details.filter(d=>d.contrato===g.contrato&&d.rodovia===g.rodovia&&(s.service==='Todos'||d.servico===s.service));return unionLen(ds.filter(d=>d.kmf>d.kmi).map(d=>[d.kmi,d.kmf]))}
function updateSummary(rows,groups,details){const km=groups.reduce((t,g)=>t+g.ext,0),roads=uniq(groups.map(g=>g.rodovia)).length,cov=groups.reduce((t,g)=>t+coverageFor(g,details),0),pct=km?Math.min(100,cov/km*100):0;$('kpiKm').textContent=kmFmt(km);$('kpiRoads').textContent=roads;$('sumKm').textContent=fmt(km);$('sumRoads').textContent=roads;$('sumStart').textContent=rows.length?'Km '+fmt(Math.min(...rows.map(x=>x.kmi))):'-';$('sumEnd').textContent=rows.length?'Km '+fmt(Math.max(...rows.map(x=>x.kmf))):'-';$('pct').textContent=fmt(pct)+'%';$('donut').style.setProperty('--p',pct);const top=groups.map(g=>({...g,cov:coverageFor(g,details)})).filter(x=>x.cov>0).sort((a,b)=>b.cov-a.cov).slice(0,5),max=top[0]?.cov||1;$('topList').innerHTML=top.length?top.map(x=>`<div><div class="top-head"><strong>${x.rodovia}</strong><span>${kmFmt(x.cov)}</span></div><div class="mini-bar"><i style="width:${x.cov/max*100}%"></i></div></div>`).join(''):'<div class="panel-meta">Sem intervalo executado localizado.</div>'}
function render(){const rows=filteredMalha(),qtyRows=filteredQty(),details=filteredDetail();let groups=groupMalha(rows);const sort=els.sort.value;if(sort==='road')groups.sort((a,b)=>a.rodovia.localeCompare(b.rodovia,'pt-BR',{numeric:true})||a.contrato.localeCompare(b.contrato));if(sort==='extDesc')groups.sort((a,b)=>b.ext-a.ext);if(sort==='extAsc')groups.sort((a,b)=>a.ext-b.ext);if(sort==='start')groups.sort((a,b)=>a.start-b.start);const pages=Math.max(1,Math.ceil(groups.length/PAGE_SIZE));page=Math.min(page,pages);const shown=groups.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE);$('meta').textContent=`${groups.length} rodovia(s) • ${rows.length} trecho(s) contratuais • ${details.length} registro(s) quilométrico(s) localizado(s)`;$('list').innerHTML=shown.length?shown.map(g=>renderRoad(g,details,qtyRows)).join(''):'<div class="empty">Nenhuma rodovia encontrada para os filtros selecionados.</div>';renderPages(pages,groups.length);updateTopKpis(qtyRows);updateSummary(rows,groups,details)}
function renderPages(pages,count){$('pageInfo').textContent=count?`Página ${page} de ${pages}`:'Sem resultados';let h=`<button class="page" ${page===1?'disabled':''} data-p="${page-1}">‹</button>`;for(let p=Math.max(1,page-2);p<=Math.min(pages,Math.max(1,page-2)+4);p++)h+=`<button class="page ${p===page?'active':''}" data-p="${p}">${p}</button>`;h+=`<button class="page" ${page===pages?'disabled':''} data-p="${page+1}">›</button>`;$('pages').innerHTML=h;$('pages').querySelectorAll('button:not([disabled])').forEach(b=>b.onclick=()=>{page=+b.dataset.p;render();window.scrollTo({top:0,behavior:'smooth'})})}
function initialize(){setOptions(els.contract,uniq(MALHA.map(x=>x.contrato)).sort(),'Todos','Todos os contratos',DEFAULT_CONTRACT);setOptions(els.road,[],'Todas','Todas as rodovias','Todas');setOptions(els.service,[],'Todos','Todas as famílias','Todos');setOptions(els.period,[],'Todos','Todos os períodos','Todos');refreshFacets();els.contract.value=DEFAULT_CONTRACT;refreshFacets();page=1;render()}
[els.contract,els.road,els.service,els.period].forEach(el=>el.addEventListener('change',()=>{refreshFacets(el.id);page=1;render()}));els.sort.addEventListener('change',()=>{page=1;render()});els.search.addEventListener('input',()=>{page=1;render()});$('clear').onclick=()=>{els.contract.value=DEFAULT_CONTRACT;els.road.value='Todas';els.service.value='Todos';els.period.value='Todos';els.sort.value='road';els.search.value='';refreshFacets();page=1;render()};initialize();